        opcao = document.createElement('option');
        opcao.text = 'Motivo:';
        document.getElementById('novocampo2').appendChild(opcao);
        opcao = document.createElement('option');
        opcao.text = 'FALHA OPERACIONAL';
        document.getElementById('novocampo2').appendChild(opcao);
        opcao = document.createElement('option');
        opcao.text = 'AGENDADA PELO CLIENTE';
        document.getElementById('novocampo2').appendChild(opcao);
        opcao = document.createElement('option');
        opcao.text = 'ATRASO NA TRANSFERÊNCIA EMBARCADORA';
        document.getElementById('novocampo2').appendChild(opcao);
        opcao = document.createElement('option');
        opcao.text = 'CLIENTE SOLICITOU RETIRADA';
        document.getElementById('novocampo2').appendChild(opcao);
        opcao = document.createElement('option');
        opcao.text = 'ATRASO NA SAÍDA/CHEGADA/DESCARGA';
        document.getElementById('novocampo2').appendChild(opcao);
        opcao = document.createElement('option');
        opcao.text = 'FERIADO';
        document.getElementById('novocampo2').appendChild(opcao);
        opcao = document.createElement('option');
        opcao.text = 'ATRASO PENDÊNCIAS';
        document.getElementById('novocampo2').appendChild(opcao);
        opcao = document.createElement('option');
        opcao.text = 'FALTA PASSAGEM FISCAL';
        document.getElementById('novocampo2').appendChild(opcao);
        opcao = document.createElement('option');
        opcao.text = 'TROCA UNIDADE SOL CLIENTE';
        document.getElementById('novocampo2').appendChild(opcao);
        opcao = document.createElement('option');
        opcao.text = 'DATA DO COMPROVANTE';
        document.getElementById('novocampo2').appendChild(opcao);
        opcao = document.createElement('option');
        opcao.text = 'CLIENTE EM BALANÇO';
        document.getElementById('novocampo2').appendChild(opcao);
        opcao = document.createElement('option');
        opcao.text = 'CLIENTE SEM EQUIPAMENTO PARA RECEBIMENTO';
        document.getElementById('novocampo2').appendChild(opcao);
        opcao = document.createElement('option');
        opcao.text = 'CLIENTE AUSENTE';
        document.getElementById('novocampo2').appendChild(opcao);
        opcao = document.createElement('option');
        opcao.text = 'CLIENTE FECHADO';
        document.getElementById('novocampo2').appendChild(opcao);
    